version: "3.8"

volumes:
  db-data:
    external: false

services:
  postgres:
    image: postgres:12
    hostname: postgres
    environment:
      restart: always
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: fake_books_test
    volumes: 
      - db-data:/usr/local/pgsql/data 
  app:
    build: .
    restart: always
    depends_on: 
      - postgres



