default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: fake_books_development

test:
  <<: *default
  database: fake_books_test
  host: <%= ENV["PG_HOST"] %>
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>

production:
  <<: *default
  database: fake_books_production
  username: ubuntu
  password: password
