default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  # username: root
  # password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: fake_books_development

test:
  <<: *default
  database: fake_books_test

production:
  <<: *default
  database: fake_books_production
  username: fake_books
  password: <%= ENV['FAKE_BOOKS_DATABASE_PASSWORD'] %>
